services:
  web24_postgres:
    image: postgres:16
    container_name: web24_postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
